services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://ghost:ghost@db:5432/appdb
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:16
    container_name: myapp-postgres
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=ghost
      - POSTGRES_PASSWORD=ghost
    ports:
      - "12345:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
